// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_n0Wft-_iO0UCJ0csqH9NPzRYi6-5HF8',
    appId: '1:111483009070:web:82469507a9533f1541c7bf',
    messagingSenderId: '111483009070',
    projectId: 'nexis-804a2',
    authDomain: 'nexis-804a2.firebaseapp.com',
    storageBucket: 'nexis-804a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeAvhWv5WijpCT4Dvij2zPLu-FJi7-Nlk',
    appId: '1:111483009070:android:1d471087251a17d241c7bf',
    messagingSenderId: '111483009070',
    projectId: 'nexis-804a2',
    storageBucket: 'nexis-804a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWnVM_-vgwwY_AQZRHwG8J5KJ57j9VV10',
    appId: '1:111483009070:ios:3088f2914f4caa9c41c7bf',
    messagingSenderId: '111483009070',
    projectId: 'nexis-804a2',
    storageBucket: 'nexis-804a2.firebasestorage.app',
    iosBundleId: 'com.example.nexis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWnVM_-vgwwY_AQZRHwG8J5KJ57j9VV10',
    appId: '1:111483009070:ios:3088f2914f4caa9c41c7bf',
    messagingSenderId: '111483009070',
    projectId: 'nexis-804a2',
    storageBucket: 'nexis-804a2.firebasestorage.app',
    iosBundleId: 'com.example.nexis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_n0Wft-_iO0UCJ0csqH9NPzRYi6-5HF8',
    appId: '1:111483009070:web:6864309131d2153a41c7bf',
    messagingSenderId: '111483009070',
    projectId: 'nexis-804a2',
    authDomain: 'nexis-804a2.firebaseapp.com',
    storageBucket: 'nexis-804a2.firebasestorage.app',
  );
}
